## mybatis的配置
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.shardingsphere

server:
  port: 8899
spring:
  shardingsphere:
    props:
      sql-show: true
      sql-comment-parse-enabled: true
    datasource:
      ds0:
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://127.0.0.1:3306/master
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      ds1:
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://127.0.0.1:3306/slave
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      names: ds0, ds1
    rules:
      readwrite-splitting:
        data-sources:
          master-slave:
            write-data-source-name: ds0
            read-data-source-names: ds1 # 可配置多个 逗号分割 比如: ds1,ds2,ds3
            load-balancer-name: load
        load-balancers:
          load:
            type: ROUND_ROBIN

