## mybatis的配置
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.shardingsphere

server:
  port: 8899
spring:
  shardingsphere:
    props:
      sql-show: true
    datasource:
      master-a:
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://127.0.0.1:3306/ds0
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      master-b:
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://127.0.0.1:3306/ds1
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      master-a-slave:
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://127.0.0.1:3306/ds2
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      master-b-slave:
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://127.0.0.1:3306/ds3
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      names: master-a, master-b, master-a-slave, master-b-slave

    rules:
      sharding:
        sharding-algorithms:
          # 分表算法
          table-inline:
            type: INLINE
            props:
              algorithm-expression: t_user$->{sharding_key % 2}
          # 分库算法
          database-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{sharding_key % 2}
        tables:
          t_user:
            actual-data-nodes: ds$->{0..1}.t_user$->{0..1}
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
            # 分表策略
            table-strategy:
              standard:
                sharding-column: sharding_key
                sharding-algorithm-name: table-inline
            # 分库策略
            database-strategy:
              standard:
                sharding-column: sharding_key
                sharding-algorithm-name: database-inline
        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 123

      readwrite-splitting:
        data-sources:
          ds0:
            write-data-source-name: master-a
            read-data-source-names: master-a-slave
            load-balancer-name: random
          ds1:
            write-data-source-name: master-b
            read-data-source-names: master-b-slave
            load-balancer-name: random
        load-balancers:
          random:
            type: RANDOM
#    mode:
#      type: cluster
#      repository:
#        type: zookeeper
#        props:
#          namespace: governance_ds
#          server-lists: localhost:2181
#          retryIntervalMilliseconds: 500
#          timeToLiveSeconds: 60
#          maxRetries: 3
#          operationTimeoutMilliseconds: 500
#      overwrite: false


