spring:
  shardingsphere:
    enabled: true
    dataSources:
      ds0:
        dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://127.0.0.1:9000/xxxx?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
        username: root
        password: xxxxxxx
    rules:
      tables:
        test_user:
          actualDataNodes: db0.test_user$->{0..1}
          tableStrategy:
            standard:
              shardingColumn: id
              shardingAlgorithmName: test-user-inline
          keyGenerateStrategy:
            column: id
            keyGeneratorName: snowflake
      shardingAlgorithms:
        test-user-inline:
          type: INLINE
          props:
            algorithm-expression: test_user$->{id % 2}
      keyGenerators:
        snowflake:
          type: SNOWFLAKE
          props:
            worker-id: 123