## mybatis的配置
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.shardingsphere


server:
  port: 8899
spring:
  shardingsphere:
#    props:
#      sql-show: true
#    datasource:
#      ds-0:
#        jdbc-url: jdbc:mysql://117.48.121.18:13306/demo_primary_ds?serverTimezone=UTC&useSSL=false
#        username: root
#        password: sphereEx@2021
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#      ds-1:
#        jdbc-url: jdbc:mysql://117.48.121.18:13307/demo_primary_ds?serverTimezone=UTC&useSSL=false
#        username: root
#        password: sphereEx@2021
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#      ds-2:
#        jdbc-url: jdbc:mysql://117.48.121.18:13308/demo_primary_ds?serverTimezone=UTC&useSSL=false
#        username: root
#        password: sphereEx@2021
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#      names: ds-0, ds-1, ds-2
#    rules:
#      readwrite-splitting:
#        data-sources:
#          rd_rs:
#            auto-aware-data-source-name: pr_ds
#      database-discovery:
#        data-sources:
#          pr_ds:
#            data-source-names: ds-0, ds-1, ds-2
#            discovery-type-name: mgr
#            discovery-heartbeat-name: mgr-heartbeat
#
#        discovery-types:
#          mgr:
#            type: MGR
#            props:
#              group-name: b13df29e-90b6-11e8-8d1b-525400fc3996
#
#        discovery-heartbeats:
#          mgr-heartbeat:
#            props:
#              keep-alive-cron: '0/5 * * * * ?'
    mode:
      type: Cluster
      repository:
        type: Zookeeper
        props:
          namespace: database_discovery
          server-lists: localhost:2181
          retryIntervalMilliseconds: 500
          timeToLiveSeconds: 60
          maxRetries: 3
          operationTimeoutMilliseconds: 500
      overwrite: true
    schema:
      name: database_discovery_db2


